# Generated by Django 3.0.8 on 2020-07-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='date published')),
                ('end_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=30)),
                ('tz', models.CharField(max_length=50)),
            ],
        ),
    ]
