# Generated by Django 3.0.8 on 2020-07-09 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=150)),
                ('tz', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='activity_periods',
        ),
        migrations.DeleteModel(
            name='members',
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='active_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='UserBackend.User'),
        ),
    ]
